import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import groupIcon from './Group.png';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Digital Finance Hub",
  description: "Generated by create next app",
  icons: {
    // Prefer the imported image's resolved URL so Next emits a proper <link>
    // tag; include type/sizes when available. Fallback to the literal path.
    icon: groupIcon?.src ? { url: groupIcon.src, type: 'image/png', sizes: `${groupIcon.width || 0}x${groupIcon.height || 0}` } : '/Group.png',
    shortcut: groupIcon?.src || '/Group.png',
    apple: groupIcon?.src || '/Group.png',
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
